language: java

jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.gradle

addons:
  chrome: stable

dist: trusty


before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=8080 http://localhost &"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - ./gradlew build
  - gradle test